name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  find-images:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.find_images.outputs.images }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Find all Docker images
        id: find_images
        run: |
          echo "images=$(ls -d */ | sed 's#/##' | grep -v '^composers$' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build-and-push:
    needs: find-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.find-images.outputs.images) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          # list of Docker images to use as base name for tags
          images: ${{ matrix.image }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value={{date 'YYYYMMDD-HHmmss' tz='Asia/Shanghai'}}
            type=raw,value=latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.image }}
          file: ${{ matrix.image }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.meta.outputs.tags }}
